/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.JOptionPane;
/**
 *
 * @author fabricio.pereira
 */
public class playerSelect extends javax.swing.JFrame {

    /**
     * Creates new form playerSelect
     */
    public playerSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLaila = new javax.swing.JLabel();
        jLabelKaiser = new javax.swing.JLabel();
        jLabelHellen = new javax.swing.JLabel();
        jLabelOdin = new javax.swing.JLabel();
        jLabelLulu = new javax.swing.JLabel();
        Laila = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        Odin = new javax.swing.JCheckBox();
        Kaiser = new javax.swing.JCheckBox();
        Hellen = new javax.swing.JCheckBox();
        Lulu = new javax.swing.JCheckBox();
        player1Select = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelLaila.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLaila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/elisabeth_02.gif"))); // NOI18N

        jLabelKaiser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelKaiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/K'_Sprite.gif"))); // NOI18N

        jLabelHellen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHellen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Leona_sprite.gif"))); // NOI18N

        jLabelOdin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOdin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/ref.gif"))); // NOI18N

        jLabelLulu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLulu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/umikeko.gif"))); // NOI18N

        Laila.setText("Laila");
        Laila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LailaActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/330px-Polaris_Player_Select.jpg"))); // NOI18N

        Odin.setText("Odin");
        Odin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdinActionPerformed(evt);
            }
        });

        Kaiser.setText("Kaiser");
        Kaiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaiserActionPerformed(evt);
            }
        });

        Hellen.setText("Hellen");
        Hellen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HellenActionPerformed(evt);
            }
        });

        Lulu.setText("Lulu");
        Lulu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuluActionPerformed(evt);
            }
        });

        player1Select.setText("Confirma");
        player1Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player1SelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabelLaila))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Laila)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelKaiser)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 116, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabelHellen, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(Hellen)
                        .addGap(103, 103, 103))))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(Kaiser)
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelOdin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabelLulu)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Odin)
                        .addGap(196, 196, 196)
                        .addComponent(Lulu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player1Select)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLaila)
                        .addGap(18, 18, 18)
                        .addComponent(Laila))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabelHellen, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelOdin, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jLabelKaiser)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Odin)
                                    .addComponent(Lulu)
                                    .addComponent(Kaiser)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Hellen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLulu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(player1Select, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LailaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LailaActionPerformed
       Hellen.setSelected(false);
       Kaiser.setSelected(false);
       Odin.setSelected(false);
       Lulu.setSelected(false);
    }//GEN-LAST:event_LailaActionPerformed

    private void HellenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HellenActionPerformed
       Laila.setSelected(false);
       Kaiser.setSelected(false);
       Odin.setSelected(false);
       Lulu.setSelected(false);    }//GEN-LAST:event_HellenActionPerformed

    private void KaiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaiserActionPerformed
       Hellen.setSelected(false);
       Laila.setSelected(false);
       Odin.setSelected(false);
       Lulu.setSelected(false);    }//GEN-LAST:event_KaiserActionPerformed

    private void OdinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdinActionPerformed
       Hellen.setSelected(false);
       Kaiser.setSelected(false);
       Laila.setSelected(false);
       Lulu.setSelected(false);    }//GEN-LAST:event_OdinActionPerformed

    private void LuluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuluActionPerformed
       Hellen.setSelected(false);
       Kaiser.setSelected(false);
       Odin.setSelected(false);
       Laila.setSelected(false);    }//GEN-LAST:event_LuluActionPerformed

    private void player1SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player1SelectActionPerformed
      telalogin2 tela = new telalogin2();
      tela.setVisible(true);
      dispose();
    
     }//GEN-LAST:event_player1SelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(playerSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(playerSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(playerSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(playerSelect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new playerSelect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Hellen;
    private javax.swing.JCheckBox Kaiser;
    private javax.swing.JCheckBox Laila;
    private javax.swing.JCheckBox Lulu;
    private javax.swing.JCheckBox Odin;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelHellen;
    private javax.swing.JLabel jLabelKaiser;
    private javax.swing.JLabel jLabelLaila;
    private javax.swing.JLabel jLabelLulu;
    private javax.swing.JLabel jLabelOdin;
    private javax.swing.JButton player1Select;
    // End of variables declaration//GEN-END:variables
}
